/**
 * 插件管家内置目录：模块名 → 中文名/说明 + 英文名/说明 + 分类。
 * 仅作为“出厂默认”——用户可在覆盖文件（~/.dsh/plugin-manager/catalog.json）中
 * 为任意模块自定义 name/desc，未收录模块显示英文短名 + 兜底说明。
 * 英文界面（评估 P2-9）优先取 nameEn/descEn；缺失时回退英文短名 + 英文兜底说明，
 * 不会把中文内容暴露给英文用户（用户自定义覆盖除外——用户数据两种语言下都生效）。
 * @module dsh-plugin-manager/catalog
 */

/** 目录条目：显示名、一句话说明（中英双语）、分类。 */
export interface CatalogEntry {
  /** 中文显示名。 */
  readonly name: string
  /** 一句话用途说明（中文）。 */
  readonly desc: string
  /** 英文显示名（评估 P2-9；缺失时英文环境回退英文短名）。 */
  readonly nameEn?: string
  /** 一句话用途说明（英文，评估 P2-9；缺失时回退英文兜底说明）。 */
  readonly descEn?: string
  /** 分组（用于界面分组展示）。 */
  readonly category: string
}

export type PluginCategory = 'core' | 'llm' | 'session' | 'agent' | 'tool' | 'skill' | 'ui' | 'web' | 'sandbox' | 'storage' | 'other'

/** 分类的双语标签（评估 P2-7：随 list() 快照下发，界面按当前语言取用）。 */
export const CATEGORY_LABELS: Record<PluginCategory, { zh: string; en: string }> = {
  core: { zh: '核心服务', en: 'Core services' },
  llm: { zh: '模型与网络', en: 'Models & network' },
  session: { zh: '会话', en: 'Sessions' },
  agent: { zh: '智能体', en: 'Agents' },
  tool: { zh: '工具', en: 'Tools' },
  skill: { zh: '技能', en: 'Skills' },
  ui: { zh: '界面', en: 'UI' },
  web: { zh: 'Web 服务', en: 'Web services' },
  sandbox: { zh: '沙箱与安全', en: 'Sandbox & security' },
  storage: { zh: '存储', en: 'Storage' },
  other: { zh: '其它', en: 'Other' },
}

/** 内置目录（键 = 模块名，即 cordis 行里的 name）。 */
export const CATALOG: Readonly<Record<string, CatalogEntry>> = {
  ["@deepseek-ai/cordis-plugin-timer"]: { name: "定时器服务", desc: "提供 delay 等定时基础能力，热加载与调度依赖它", nameEn: "Timer service", descEn: "Provides delay and other basic timing capabilities; hot reload and scheduling depend on it", category: "core" as PluginCategory },
  ["@deepseek-ai/cordis-plugin-hmr"]: { name: "热加载驱动", desc: "监听配置文件与插件变更并热重载（Web 端默认停用）", nameEn: "Hot reload driver", descEn: "Watches config and plugin changes and hot-reloads them (disabled by default on web)", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-llm"]: { name: "大模型服务接口", desc: "统一的模型调用接口层，所有模型适配器都挂在它下面", nameEn: "LLM service interface", descEn: "Unified model invocation layer; all model adapters hang off it", category: "llm" as PluginCategory },
  ["@deepseek-ai/dsh-session"]: { name: "会话存储核心", desc: "事件溯源式会话数据核心，记录整个对话轨迹", nameEn: "Session store core", descEn: "Event-sourced session data core recording the whole conversation", category: "session" as PluginCategory },
  ["@deepseek-ai/dsh-typert-registry"]: { name: "类型反射注册表", desc: "运行时的包反射与 Zod 模式注册中心（RPC 依赖）", nameEn: "Typert registry", descEn: "Runtime package reflection and Zod schema registry (RPC dependency)", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-typert-loader"]: { name: "类型反射加载器", desc: "把生成的 Typert 包贡献加载进加载器", nameEn: "Typert loader", descEn: "Loads generated Typert package contributions into the loader", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-api-gateway"]: { name: "API 网关", desc: "远程调用（RPC）的主机分发与客户端接口", nameEn: "API gateway", descEn: "Host dispatch and client interface for remote calls (RPC)", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-session-title"]: { name: "会话标题服务", desc: "基于会话记录生成标题的服务与提供者注册", nameEn: "Session title service", descEn: "Title generation service and provider registration based on session records", category: "session" as PluginCategory },
  ["@deepseek-ai/dsh-session-title-first-prompt-llm"]: { name: "会话标题生成（LLM）", desc: "用第一条消息让大模型生成会话标题", nameEn: "Session title (LLM)", descEn: "Has an LLM generate the session title from the first message", category: "session" as PluginCategory },
  ["@deepseek-ai/dsh-user-questions"]: { name: "用户提问通道", desc: "向用户提问的抽象接口（Agent 运行中征求确认用）", nameEn: "User question channel", descEn: "Abstract interface for asking the user questions (agent confirmations)", category: "agent" as PluginCategory },
  ["@deepseek-ai/dsh-agent"]: { name: "智能体核心", desc: "Agent 接口、注册表与会话事件词汇", nameEn: "Agent core", descEn: "Agent interfaces, registries and session event vocabulary", category: "agent" as PluginCategory },
  ["@deepseek-ai/dsh-agent-default-model"]: { name: "默认模型选择", desc: "Agent 入口共享的默认模型选择服务", nameEn: "Default model picker", descEn: "Default model selection service shared by agent entries", category: "llm" as PluginCategory },
  ["@deepseek-ai/dsh-jobs-local"]: { name: "后台任务注册表", desc: "进程内后台任务（job）注册与管理", nameEn: "Local jobs registry", descEn: "In-process background job registration and management", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-llm-retry"]: { name: "模型请求重试", desc: "按提供商路由的 LLM 请求重试策略", nameEn: "LLM request retry", descEn: "Per-provider retry policies for LLM requests", category: "llm" as PluginCategory },
  ["@deepseek-ai/dsh-settings-file"]: { name: "设置存储（文件）", desc: "把设置写入 settings.yaml 的文件后端", nameEn: "File settings store", descEn: "File backend persisting settings into settings.yaml", category: "storage" as PluginCategory },
  ["@deepseek-ai/dsh-credentials-local"]: { name: "凭据存储（本地）", desc: "本地凭据提供者（.credentials.yaml / .env）", nameEn: "Local credentials store", descEn: "Local credential provider (.credentials.yaml / .env)", category: "storage" as PluginCategory },
  ["@deepseek-ai/dsh-llm-pi-ai"]: { name: "pi-ai 模型适配器", desc: "基于 pi-ai 的多提供商模型适配（自定义 API 基址）", nameEn: "pi-ai model adapter", descEn: "Multi-provider model adapter based on pi-ai (custom API base URLs)", category: "llm" as PluginCategory },
  ["@deepseek-ai/dsh-session-persistence-jsonl"]: { name: "会话持久化（JSONL）", desc: "把会话记录以 JSONL 文件持久化保存", nameEn: "Session persistence (JSONL)", descEn: "Persists session records as JSONL files", category: "session" as PluginCategory },
  ["@deepseek-ai/dsh-attachment-local"]: { name: "附件存储", desc: "内容寻址的附件本地存储", nameEn: "Attachment store", descEn: "Content-addressed local attachment storage", category: "storage" as PluginCategory },
  ["@deepseek-ai/dsh-session-query-sqlite"]: { name: "会话全文搜索", desc: "SQLite FTS5 全文检索会话内容", nameEn: "Session full-text search", descEn: "SQLite FTS5 full-text search over session content", category: "session" as PluginCategory },
  ["@deepseek-ai/dsh-session-projection"]: { name: "会话投影", desc: "会话数据的可合并扩展投影类型表", nameEn: "Session projections", descEn: "Mergeable extension projection types for session data", category: "session" as PluginCategory },
  ["@deepseek-ai/dsh-session-telemetry-otel"]: { name: "遥测上报", desc: "把会话记录交给 OpenTelemetry 上报（可关闭）", nameEn: "Session telemetry (OTel)", descEn: "Hands session records to OpenTelemetry reporting (opt-out)", category: "session" as PluginCategory },
  ["@deepseek-ai/dsh-subprocess-local"]: { name: "子进程执行", desc: "本地子进程执行实现", nameEn: "Subprocess runner", descEn: "Local subprocess execution implementation", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-sandbox-local"]: { name: "进程沙箱", desc: "本地进程沙箱后端（bwrap / landlock 等）", nameEn: "Process sandbox", descEn: "Local process sandbox backend (bwrap / landlock etc.)", category: "sandbox" as PluginCategory },
  ["@deepseek-ai/dsh-sandbox-policy"]: { name: "沙箱策略", desc: "每次调用的沙箱策略解析（权限模式/工作区根）", nameEn: "Sandbox policy", descEn: "Per-call sandbox policy resolution (permission mode / workspace root)", category: "sandbox" as PluginCategory },
  ["@deepseek-ai/dsh-bash-sandbox"]: { name: "Bash 执行器（沙箱）", desc: "通过沙箱执行 Bash 命令（Windows 下默认停用）", nameEn: "Bash runner (sandboxed)", descEn: "Runs Bash commands through the sandbox (disabled by default on Windows)", category: "sandbox" as PluginCategory },
  ["@deepseek-ai/dsh-pwsh-sandbox"]: { name: "PowerShell 执行器（沙箱）", desc: "通过沙箱执行 PowerShell 命令（Windows 专用）", nameEn: "PowerShell runner (sandboxed)", descEn: "Runs PowerShell commands through the sandbox (Windows only)", category: "sandbox" as PluginCategory },
  ["@deepseek-ai/dsh-user-approval"]: { name: "操作审批", desc: "危险操作的一次性权限审批通道", nameEn: "Operation approval", descEn: "One-shot approval channel for dangerous operations", category: "sandbox" as PluginCategory },
  ["@deepseek-ai/dsh-permission-presets"]: { name: "权限预设", desc: "面向用户的权限预设（只读/工作区写/完全访问）", nameEn: "Permission presets", descEn: "User-facing permission presets (read-only / workspace-write / full access)", category: "sandbox" as PluginCategory },
  ["@deepseek-ai/dsh-shell-env"]: { name: "Shell 环境注册", desc: "管理注入 shell 的 DSH_* 环境变量", nameEn: "Shell environment registry", descEn: "Manages the DSH_* environment variables injected into shells", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-tool-bash"]: { name: "Bash 工具", desc: "给模型用的 bash 命令工具（Web 端默认停用）", nameEn: "Bash tool", descEn: "Bash command tool for the model (disabled by default on web)", category: "tool" as PluginCategory },
  ["@deepseek-ai/dsh-tool-pwsh"]: { name: "PowerShell 工具", desc: "给模型用的 pwsh 命令工具（Web 端默认停用）", nameEn: "PowerShell tool", descEn: "pwsh command tool for the model (disabled by default on web)", category: "tool" as PluginCategory },
  ["@deepseek-ai/dsh-tool-jobs"]: { name: "后台任务工具", desc: "job_output / job_list / job_kill 工具（Web 端默认停用）", nameEn: "Jobs tools", descEn: "job_output / job_list / job_kill tools (disabled by default on web)", category: "tool" as PluginCategory },
  ["@deepseek-ai/dsh-fs-observation-policy"]: { name: "文件观察策略", desc: "文件上下文策略：读取前观察、编辑前先读等", nameEn: "File observation policy", descEn: "File context policy: observe before reads, read before edits, etc.", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-tool-fs"]: { name: "文件工具", desc: "read / write / edit 文件操作工具（Web 端默认停用）", nameEn: "File tools", descEn: "read / write / edit file operation tools (disabled by default on web)", category: "tool" as PluginCategory },
  ["@deepseek-ai/dsh-tool-fs-search"]: { name: "文件搜索工具", desc: "glob / grep 文件发现工具（内置 ripgrep）", nameEn: "File search tool", descEn: "glob / grep file discovery tools (bundled ripgrep)", category: "tool" as PluginCategory },
  ["@deepseek-ai/dsh-agent-instructions"]: { name: "工作区指令加载", desc: "加载 AGENTS.md / CLAUDE.md 项目指令", nameEn: "Workspace instructions", descEn: "Loads AGENTS.md / CLAUDE.md project instructions", category: "agent" as PluginCategory },
  ["@deepseek-ai/dsh-skill"]: { name: "技能注册中心", desc: "Agent 技能（skill）提供者注册表", nameEn: "Skill registry", descEn: "Provider registry for agent skills", category: "skill" as PluginCategory },
  ["@deepseek-ai/dsh-skill-filesystem"]: { name: "技能文件系统", desc: "从本地目录加载技能文件", nameEn: "Skill filesystem", descEn: "Loads skill files from local directories", category: "skill" as PluginCategory },
  ["@deepseek-ai/dsh-skill-badge"]: { name: "DSH 徽章技能", desc: "内置的 dsh 徽章技能提供者", nameEn: "DSH badge skill", descEn: "Built-in dsh badge skill provider", category: "skill" as PluginCategory },
  ["@deepseek-ai/dsh-tool-skill"]: { name: "技能工具", desc: "给模型用的 skill 加载工具", nameEn: "Skill tool", descEn: "Skill loading tool for the model", category: "skill" as PluginCategory },
  ["@deepseek-ai/dsh-commands"]: { name: "命令注册表", desc: "插件持有的人类命令注册（斜杠命令）", nameEn: "Command registry", descEn: "Registration of human-facing commands held by plugins (slash commands)", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-command-feedback"]: { name: "反馈命令", desc: "会话反馈记录 + /feedback 斜杠命令", nameEn: "Feedback command", descEn: "Session feedback records + the /feedback slash command", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-goal"]: { name: "目标状态服务", desc: "同会话目标（goal）的事件溯源状态与生命周期", nameEn: "Goal state service", descEn: "Event-sourced state and lifecycle for session-scoped goals", category: "agent" as PluginCategory },
  ["@deepseek-ai/dsh-goal-round-driver"]: { name: "目标轮次驱动", desc: "目标自动续轮驱动器", nameEn: "Goal round driver", descEn: "Driver that automatically continues goal rounds", category: "agent" as PluginCategory },
  ["@deepseek-ai/dsh-command-goal"]: { name: "目标命令", desc: "人类用的目标斜杠命令", nameEn: "Goal command", descEn: "Goal slash commands for humans", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-plan-mode"]: { name: "计划模式", desc: "按会话记录的计划模式（先计划后执行）", nameEn: "Plan mode", descEn: "Session-record-backed plan mode (plan first, then execute)", category: "agent" as PluginCategory },
  ["@deepseek-ai/dsh-token-meter"]: { name: "Token 计量", desc: "回放感知的 token 消耗测量服务", nameEn: "Token meter", descEn: "Replay-aware token consumption metering service", category: "llm" as PluginCategory },
  ["@deepseek-ai/dsh-compaction-basic"]: { name: "上下文压缩", desc: "按 token 阈值自动压缩会话上下文", nameEn: "Context compaction", descEn: "Auto-compacts session context at token thresholds", category: "session" as PluginCategory },
  ["@deepseek-ai/dsh-command-compact"]: { name: "压缩命令", desc: "人类手动触发会话压缩的斜杠命令", nameEn: "Compact command", descEn: "Slash command for manually triggering session compaction", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-subagent"]: { name: "子代理接口", desc: "委托子代理（subagent）的命名提供者注册", nameEn: "Subagent interface", descEn: "Named provider registry for delegating subagents", category: "agent" as PluginCategory },
  ["@deepseek-ai/dsh-subagent-spawn-in-process"]: { name: "子代理（进程内）", desc: "进程内生成全新子代理的后端", nameEn: "Subagent (in-process)", descEn: "Backend spawning fresh subagents in-process", category: "agent" as PluginCategory },
  ["@deepseek-ai/dsh-subagent-fork-in-process"]: { name: "子代理（分叉）", desc: "继承父会话前缀的分叉子代理后端", nameEn: "Subagent (fork)", descEn: "Backend forking subagents that inherit the parent session prefix", category: "agent" as PluginCategory },
  ["@deepseek-ai/dsh-tool-subagent-control"]: { name: "子代理控制工具", desc: "send_message / interrupt_agent / list_agents 工具", nameEn: "Subagent control tool", descEn: "send_message / interrupt_agent / list_agents tools", category: "agent" as PluginCategory },
  ["@deepseek-ai/dsh-tool-subagent-control/list-agents"]: { name: "子代理控制工具（列表）", desc: "同一子代理控制工具包的列表入口", nameEn: "Subagent control (list)", descEn: "List entry of the same subagent control tool package", category: "agent" as PluginCategory },
  ["@deepseek-ai/dsh-tool-subagent"]: { name: "子代理委托工具", desc: "给模型用的 subagent 委托工具", nameEn: "Subagent delegation tool", descEn: "Subagent delegation tool for the model", category: "agent" as PluginCategory },
  ["@deepseek-ai/dsh-tool-subagent-fork"]: { name: "子代理分叉工具", desc: "给模型用的分叉式 subagent 工具", nameEn: "Subagent fork tool", descEn: "Fork-style subagent tool for the model", category: "agent" as PluginCategory },
  ["@deepseek-ai/dsh-tool-subagent-report"]: { name: "子代理报告工具", desc: "子代理作用域内的结果上报工具", nameEn: "Subagent report tool", descEn: "Result reporting tool scoped to subagents", category: "agent" as PluginCategory },
  ["@deepseek-ai/dsh-workflow-worker-thread"]: { name: "工作流引擎", desc: "在 worker 线程中执行编排脚本的工作流引擎", nameEn: "Workflow engine", descEn: "Workflow engine running orchestration scripts in worker threads", category: "agent" as PluginCategory },
  ["@deepseek-ai/dsh-tool-workflow"]: { name: "工作流工具", desc: "给模型用的 workflow 编排脚本工具", nameEn: "Workflow tool", descEn: "Workflow orchestration script tool for the model", category: "tool" as PluginCategory },
  ["@deepseek-ai/dsh-tool-call-timeout-policy"]: { name: "工具超时策略", desc: "工具调用超时策略（按工具类型设定时限）", nameEn: "Tool timeout policy", descEn: "Tool call timeout policy (per tool type limits)", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-spill-local"]: { name: "溢写存储（本地）", desc: "超大工具结果溢写到本地文件", nameEn: "Local spill store", descEn: "Spills oversized tool results to local files", category: "storage" as PluginCategory },
  ["@deepseek-ai/dsh-spill-policy"]: { name: "溢写策略", desc: "把超长工具结果替换为文件引用", nameEn: "Spill policy", descEn: "Replaces overlong tool results with file references", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-session-checkpoint-policy"]: { name: "会话检查点", desc: "模型请求与工具副作用前的持久化检查点", nameEn: "Session checkpoint", descEn: "Persistent checkpoints before model requests and tool side effects", category: "session" as PluginCategory },
  ["@deepseek-ai/dsh-compaction-tool-result-pruner"]: { name: "结果裁剪", desc: "回放安全地裁剪工具结果（头部/中部/尾部）", nameEn: "Result pruner", descEn: "Replay-safely prunes tool results (head / middle / tail)", category: "session" as PluginCategory },
  ["@deepseek-ai/dsh-tool-todo"]: { name: "待办工具", desc: "给模型用的 todo_write 待办列表工具", nameEn: "Todo tool", descEn: "todo_write todo-list tool for the model", category: "tool" as PluginCategory },
  ["@deepseek-ai/dsh-tool-goal"]: { name: "目标工具", desc: "给模型用的同会话目标工具（含权限检查）", nameEn: "Goal tool", descEn: "Session goal tool for the model (with permission checks)", category: "tool" as PluginCategory },
  ["@deepseek-ai/dsh-tool-ralph"]: { name: "Ralph 循环工具", desc: "给模型用的 Ralph 全新代理迭代循环", nameEn: "Ralph loop tool", descEn: "Ralph fresh-agent iteration loop tool for the model", category: "tool" as PluginCategory },
  ["@deepseek-ai/dsh-tool-str-replace-editor"]: { name: "字符串编辑工具", desc: "view/create/替换/插入行的文本编辑工具", nameEn: "Str-replace editor", descEn: "Text editing tool with view/create/replace/insert-lines operations", category: "tool" as PluginCategory },
  ["@deepseek-ai/dsh-repeat-tool-reminder"]: { name: "重复调用提醒", desc: "模型重复调用同一工具时给出提醒", nameEn: "Repeat call reminder", descEn: "Reminds when the model repeatedly calls the same tool", category: "agent" as PluginCategory },
  ["@deepseek-ai/dsh-web"]: { name: "网络能力接口", desc: "搜索/抓取能力的抽象接口与提供者注册", nameEn: "Web capability interface", descEn: "Abstract interface and provider registry for search/fetch", category: "llm" as PluginCategory },
  ["@deepseek-ai/dsh-web-search-deepseek"]: { name: "DeepSeek 搜索", desc: "DeepSeek 官方搜索提供者（web_search）", nameEn: "DeepSeek search", descEn: "Official DeepSeek search provider (web_search)", category: "llm" as PluginCategory },
  ["@deepseek-ai/dsh-tool-web"]: { name: "网络工具", desc: "给模型用的 web_search / web_fetch 工具", nameEn: "Web tools", descEn: "web_search / web_fetch tools for the model", category: "tool" as PluginCategory },
  ["@deepseek-ai/dsh-tools"]: { name: "工具注册中心", desc: "工具注册表与执行管线（所有 tool_* 的宿主）", nameEn: "Tools registry", descEn: "Tool registry and execution pipeline (host of all tool_*)", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-system-prompt"]: { name: "系统提示词组装", desc: "系统提示词分节组装注册表", nameEn: "System prompt builder", descEn: "Registry for assembling system prompt sections", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-agent-loop"]: { name: "Agent 主循环", desc: "具体 Agent 循环（思考-调用工具-产出）实现", nameEn: "Agent loop", descEn: "Concrete agent loop implementation (think - call tools - produce)", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-fs-sandbox"]: { name: "文件沙箱执行", desc: "按沙箱策略拦截 write/edit 的文件系统实现", nameEn: "Filesystem sandbox", descEn: "Filesystem implementation intercepting write/edit per sandbox policy", category: "sandbox" as PluginCategory },
  ["@deepseek-ai/dsh-llm-deepseek"]: { name: "DeepSeek 模型适配器", desc: "DeepSeek 官方 chat-completions 模型适配", nameEn: "DeepSeek model adapter", descEn: "Official DeepSeek chat-completions model adapter", category: "llm" as PluginCategory },
  ["@deepseek-ai/dsh-code-runtime-worker-thread"]: { name: "代码执行运行时", desc: "在 worker 线程中执行代码的运行时", nameEn: "Code execution runtime", descEn: "Runtime executing code in worker threads", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-storage"]: { name: "存储中枢", desc: "命名存储后端注册与数据形态设施", nameEn: "Storage hub", descEn: "Named storage backend registry and data shape facilities", category: "storage" as PluginCategory },
  ["@deepseek-ai/dsh-storage-json"]: { name: "JSON 存储后端", desc: "JSON 文件 KV 存储后端", nameEn: "JSON storage backend", descEn: "JSON-file KV storage backend", category: "storage" as PluginCategory },
  ["@deepseek-ai/dsh-storage-domain"]: { name: "领域存储", desc: "带模式校验的 KV 领域数据存储", nameEn: "Domain storage", descEn: "Schema-validated KV domain data storage", category: "storage" as PluginCategory },
  ["@deepseek-ai/dsh-message-feedback"]: { name: "消息反馈", desc: "每条消息的点赞/点踩与备注", nameEn: "Message feedback", descEn: "Per-message like/dislike and notes", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-session-log-export"]: { name: "会话导出", desc: "Web 端会话日志导出与下载对话框", nameEn: "Session export", descEn: "Web session log export and download dialog", category: "session" as PluginCategory },
  ["@deepseek-ai/dsh-workspace"]: { name: "工作区注册", desc: "工作区（workspace）实体注册与会话挂接", nameEn: "Workspace registry", descEn: "Workspace entity registration and session attachment", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-session-projection-cache"]: { name: "投影缓存", desc: "会话投影的持久化检查点缓存", nameEn: "Projection cache", descEn: "Persistent checkpoint cache for session projections", category: "session" as PluginCategory },
  ["@deepseek-ai/dsh-session-stats"]: { name: "会话统计", desc: "整个会话日志的轮次/耗时统计投影", nameEn: "Session stats", descEn: "Round/duration statistics projection over the whole session log", category: "session" as PluginCategory },
  ["@deepseek-ai/dsh-host-directory-picker-auto"]: { name: "目录选择器", desc: "按宿主环境自动选择原生/浏览式目录选择", nameEn: "Directory picker", descEn: "Picks native or browser-style directory selection per host environment", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-host-plugin-inventory"]: { name: "插件清单服务（只读）", desc: "把 Cordis 加载器插件状态投影给客户端（只读）", nameEn: "Plugin inventory service (read-only)", descEn: "Projects Cordis loader plugin state to the client (read-only)", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-host-apiproxy"]: { name: "API 网关宿主", desc: "API 网关：/api 契约、fetch 载体与主机插件", nameEn: "API gateway host", descEn: "API gateway: /api contract, fetch carrier and host plugin", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-cordis-host-runner"]: { name: "动态插件宿主", desc: "AI 动态定义插件的注册、沙箱与调用处理器", nameEn: "Dynamic plugin host", descEn: "Registration, sandboxing and invocation handlers for AI-defined plugins", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-web-app/startup"]: { name: "Web 启动参数", desc: "解析 Web 启动参数（host/port/信任主机等）", nameEn: "Web startup options", descEn: "Parses web startup options (host / port / trusted hosts etc.)", category: "web" as PluginCategory },
  ["@deepseek-ai/dsh-host-webserver"]: { name: "HTTP 服务器", desc: "Web 路由注册与静态资源服务", nameEn: "HTTP server", descEn: "Web route registration and static asset serving", category: "web" as PluginCategory },
  ["@deepseek-ai/dsh-web-app"]: { name: "Web 运行时", desc: "Web 界面运行时（前端静态资源、信任栅栏）", nameEn: "Web runtime", descEn: "Web UI runtime (frontend assets, trust barrier)", category: "web" as PluginCategory },
  ["@deepseek-ai/dsh-client-hmr"]: { name: "客户端热更新", desc: "开发模式下客户端插件热更新驱动", nameEn: "Client hot reload", descEn: "Hot reload driver for client plugins in development mode", category: "web" as PluginCategory },
  ["@deepseek-ai/dsh-client-modules"]: { name: "客户端模块系统", desc: "浏览器插件模块表与 __DSH_BOOT__ 组装", nameEn: "Client module system", descEn: "Browser plugin module table and __DSH_BOOT__ assembly", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-client-connection"]: { name: "客户端连接", desc: "浏览器与主机的 HTTP/WebSocket 连接层", nameEn: "Client connection", descEn: "HTTP/WebSocket connection layer between browser and host", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-api-remotes"]: { name: "远程接口装配", desc: "把主机远程服务装配给浏览器（remote.*）", nameEn: "Remote assembly", descEn: "Assembles host remote services for the browser (remote.*)", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-client-runtime"]: { name: "客户端运行时", desc: "浏览器核心服务：会话运行时与槽位注册", nameEn: "Client runtime", descEn: "Browser core services: session runtime and slot registration", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-cordis-client-runner"]: { name: "动态插件客户端", desc: "AI 动态定义插件的浏览器半执行环境", nameEn: "Dynamic plugin client", descEn: "Browser-side execution environment for AI-defined plugins", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-theme"]: { name: "主题", desc: "明暗主题状态与切换", nameEn: "Theme", descEn: "Light/dark theme state and switching", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-locale"]: { name: "语言", desc: "中/英语言偏好与文案字典", nameEn: "Language", descEn: "Chinese/English language preference and copy dictionaries", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-layout"]: { name: "界面框架", desc: "三栏应用框架与拖拽调节、面板状态", nameEn: "App layout", descEn: "Three-column app shell with drag resizing and panel state", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-sidebar"]: { name: "侧边栏", desc: "会话多级树、搜索、分组与状态点", nameEn: "Sidebar", descEn: "Session tree, search, grouping and status dots", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-settings"]: { name: "设置框架", desc: "设置页的命名空间作用域与槽位契约", nameEn: "Settings shell", descEn: "Namespace scoping and slot contracts for the settings page", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-settings-general"]: { name: "常规设置", desc: "常规设置分区与新手引导", nameEn: "General settings", descEn: "General settings section and onboarding", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-settings-models"]: { name: "模型设置", desc: "模型配置设置与凭据接入对话框", nameEn: "Model settings", descEn: "Model configuration settings and credential onboarding dialog", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-settings-plugin-inventory"]: { name: "插件列表页（只读）", desc: "设置里的只读插件清单标签页", nameEn: "Plugin list page (read-only)", descEn: "Read-only plugin inventory tab in settings", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-conversation"]: { name: "对话界面", desc: "对话区骨架、消息流、输入框与详情", nameEn: "Conversation UI", descEn: "Conversation skeleton, message stream, composer and details", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-tool"]: { name: "工具调用卡片", desc: "工具调用树的渲染与按工具定制视图", nameEn: "Tool call cards", descEn: "Renders the tool call tree with per-tool custom views", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-cordis"]: { name: "动态插件卡片", desc: "cordis_define 工具行的运行/停止开关卡片", nameEn: "Dynamic plugin cards", descEn: "Run/stop toggle cards for cordis_define tool rows", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-workflow-run"]: { name: "工作流运行节点", desc: "工作流运行生命周期对话节点", nameEn: "Workflow run nodes", descEn: "Conversation nodes for the workflow run lifecycle", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-deliverables"]: { name: "产出文件栏", desc: "回复尾部产出文件引用与点击打开", nameEn: "Deliverables bar", descEn: "End-of-reply deliverable file references with click-to-open", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-workspace"]: { name: "工作区选择器", desc: "侧边栏里的工作区选择组件", nameEn: "Workspace picker", descEn: "Workspace selection component in the sidebar", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-input-trigger"]: { name: "输入触发器", desc: "'/' 与 '@' 触发管线与候选菜单", nameEn: "Input triggers", descEn: "Trigger pipelines and candidate menus for '/' and '@'", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-commands"]: { name: "命令面板", desc: "全局命令目录与 '/' 命令源、弹层选择", nameEn: "Command palette", descEn: "Global command catalog, '/' command source and overlay picker", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-skill"]: { name: "技能引用", desc: "Web 端技能引用与技能工具行", nameEn: "Skill references", descEn: "Web skill references and skill tool rows", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-subagent"]: { name: "子代理界面", desc: "子代理会话目录、续接路由与 '@' 引用源", nameEn: "Subagent UI", descEn: "Subagent session directory, continuation routing and '@' reference source", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-jobs"]: { name: "后台任务列表", desc: "会话头的后台任务实时列表", nameEn: "Jobs list", descEn: "Live background job list in the session header", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-goal"]: { name: "目标条", desc: "输入框上方的会话目标条（GoalBar）", nameEn: "Goal bar", descEn: "Session goal bar above the composer (GoalBar)", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-message-feedback"]: { name: "消息反馈按钮", desc: "助手消息操作条上的点赞/点踩与备注", nameEn: "Message feedback buttons", descEn: "Like/dislike and notes on the assistant message action bar", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-model-selection"]: { name: "模型选择", desc: "/model 弹层选择与会话模型切换", nameEn: "Model selection", descEn: "The /model overlay picker and per-session model switching", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-permission-presets"]: { name: "权限界面", desc: "新会话默认权限与 /permission 弹层", nameEn: "Permission UI", descEn: "New-session default permissions and the /permission overlay", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-agent-preset"]: { name: "Agent 预设界面", desc: "默认/当前会话的 Agent 预设与组合编辑器", nameEn: "Agent preset UI", descEn: "Agent presets and composition editor for default/current session", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-settings-plugins"]: { name: "插件设置分区", desc: "设置→插件 分区与可配置插件卡片", nameEn: "Plugin settings section", descEn: "The settings→plugins section and configurable plugin cards", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-plan"]: { name: "计划模式控件", desc: "输入框上的计划模式开关与 /plan 命令", nameEn: "Plan mode controls", descEn: "Plan mode toggle above the composer and the /plan command", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-user-questions"]: { name: "提问界面", desc: "ask_user_question 的输入框接管提问 UI", nameEn: "Question UI", descEn: "Composer-taking-over question UI for ask_user_question", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-trajectory"]: { name: "轨迹视图", desc: "交互式时序轨迹事件总览", nameEn: "Trajectory view", descEn: "Interactive chronological overview of trajectory events", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-agent-presets"]: { name: "Agent 预设引擎", desc: "按预设 cordis.yml 组合每个会话的 Agent", nameEn: "Agent preset engine", descEn: "Composes each session's agent from preset cordis.yml", category: "agent" as PluginCategory },
  // ===== PerryLink 插件中文名/描述（数据源：PerryLink/dsh-catalog data/packages.json + 各仓库 README/npm registry 实测）=====
  // 键 = 模块名（npm 包名，即 cordis 行 name）；category 一律按功能分组，
  // 官方/社区归属由 scope 推断（src/origin.ts），不占用分类维度。
  ["dsh-auto-review"]: { name: "自动审查", desc: "审批链上的第二模型自动审查：只读 reviewer 子代理给出 allow/deny 结构化判定，默认 fail-closed，全程会话日志可审计。", nameEn: "Auto review", descEn: "Second-model review on the approval chain: a read-only reviewer subagent returns structured allow/deny verdicts, fail-closed by default, fully auditable in the session log.", category: "agent" as PluginCategory },
  ["dsh-permission-rules"]: { name: "权限规则", desc: "声明式有序 allow/deny/ask 权限规则：匹配工具名、参数（glob/正则）、工作区路径与网络目标（域名/IP/端口/协议），外加 Codex 风格进程级网络策略。", nameEn: "Permission rules", descEn: "Declarative ordered allow/deny/ask rules matching tool names, arguments (glob/regex), workspace paths and network targets (domain/IP/port/protocol), plus Codex-style process-level network policies.", category: "sandbox" as PluginCategory },
  ["dsh-doublecheck"]: { name: "双重校验", desc: "交付质量门：动笔前审讯需求、红绿测试证据、交付后对抗评审，最终给出 deliverable/rework 放行判定。", nameEn: "Double check", descEn: "Delivery quality gate: interrogates requirements before work starts, requires red/green test evidence, runs an adversarial review after delivery, and issues a deliverable/rework verdict.", category: "tool" as PluginCategory },
  ["dsh-memento"]: { name: "记忆", desc: "有界、分层、带审批门、可审计的跨会话记忆：ctx.memory 能力缝 + 本地 SQLite 提供者 + memory 工具 + 冻结快照注入。", nameEn: "Memory", descEn: "Bounded, layered, approval-gated and auditable cross-session memory: ctx.memory capability seam + local SQLite provider + memory tools + frozen snapshot injection.", category: "session" as PluginCategory },
  ["dsh-checkpoint-rewind"]: { name: "检查点回退", desc: "统一 DSH 检查点：会话/工作区/配置三态快照 + /checkpoint、/rewind 一键回退 + 设置页时间线 diff + 种子回放恢复。", nameEn: "Checkpoint & rewind", descEn: "Unified DSH checkpoints: session/workspace/config snapshots + one-click /checkpoint and /rewind + a settings-page timeline diff + seed-replay restore.", category: "session" as PluginCategory },
  ["dsh-mcp-panel"]: { name: "MCP 面板", desc: "MCP 服务器管理面板：查看状态、启停、日志、配置与工具试调，带自动备份。", nameEn: "MCP panel", descEn: "MCP server management panel: status, enable/disable, logs, config and tool trial calls, with automatic backups.", category: "tool" as PluginCategory },
  ["dsh-composer-history"]: { name: "输入历史", desc: "Web 输入框的终端式输入历史：方向键精确恢复草稿与光标、浏览器本地持久化、Ctrl+R 反查、工作区召回、压缩感知。", nameEn: "Input history", descEn: "Terminal-style input history for the web composer: arrow-key draft and cursor restore, browser-local persistence, Ctrl+R reverse search, workspace recall and compaction awareness.", category: "ui" as PluginCategory },
  ["dsh-session-pin"]: { name: "会话置顶", desc: "置顶重要会话：保持可见、排序靠前、避免被清理。", nameEn: "Session pin", descEn: "Pin important sessions: keep them visible, sorted first and safe from cleanup.", category: "session" as PluginCategory },
  ["dsh-session-sync"]: { name: "会话同步", desc: "会话日志推送/拉取到远程存储，支持可配置的自动同步。", nameEn: "Session sync", descEn: "Push/pull session logs to remote storage with configurable auto-sync.", category: "session" as PluginCategory },
  ["dsh-output-styles"]: { name: "输出样式", desc: "运行时切换模型输出样式：内置六款样式库、/style 命令、会话级持久化、系统提示词注入与渲染器注册表。", nameEn: "Output styles", descEn: "Switch model output styles at runtime: six built-in styles, the /style command, session-level persistence, system-prompt injection and a renderer registry.", category: "ui" as PluginCategory },
  ["dsh-lsp-actions"]: { name: "LSP 动作", desc: "语言服务器能力暴露给 agent：诊断、定义、引用、补全、code actions 与整仓重命名。", nameEn: "LSP actions", descEn: "Exposes language-server capabilities to agents: diagnostics, definitions, references, completions, code actions and whole-repo renames.", category: "tool" as PluginCategory },
  ["dsh-background-agents"]: { name: "后台子代理", desc: "后台持久子代理：结构化任务板、进度监控、随时消息与中断控制。", nameEn: "Background agents", descEn: "Persistent background subagents: structured task board, progress monitoring, messaging at any time and interrupt control.", category: "agent" as PluginCategory },
  ["dsh-claude-move"]: { name: "Claude 迁移", desc: "Claude Code/Codex/OpenCode/Hermes → DSH 迁移：导入 CLAUDE.md/AGENTS.md、斜杠命令与会话历史，审批门 + 幂等。", nameEn: "Claude migration", descEn: "Migrates Claude Code/Codex/OpenCode/Hermes → DSH: imports CLAUDE.md/AGENTS.md, slash commands and session history; approval-gated and idempotent.", category: "tool" as PluginCategory },
  ["dsh-translate"]: { name: "翻译", desc: "会话内翻译文本与文件并做质量校验；顺带修复模型产出的坏 JSON。", nameEn: "Translate", descEn: "Translates text and files in-session with quality checks; also repairs broken model-emitted JSON.", category: "tool" as PluginCategory },
  ["dsh-local-ai"]: { name: "本地模型", desc: "把 Ollama / LM Studio / 本地端点变成 DSH 的直接模型路由。", nameEn: "Local AI", descEn: "Turns Ollama / LM Studio / local endpoints into direct DSH model routes.", category: "llm" as PluginCategory },
  ["dsh-mask"]: { name: "脱敏", desc: "敏感值遮蔽：密钥遮蔽规则 + 内存白名单 + 受控揭示流程。", nameEn: "Masking", descEn: "Sensitive-value masking: secret masking rules + in-memory allowlist + controlled reveal flow.", category: "tool" as PluginCategory },
  ["dsh-data-quality"]: { name: "数据质量", desc: "确定性数据画像、清洗与核验：DAMA 记分卡、内容哈希去重、指标期望与漂移检查。", nameEn: "Data quality", descEn: "Deterministic data profiling, cleaning and verification: DAMA scorecards, content-hash dedup, metric expectations and drift checks.", category: "tool" as PluginCategory },
  ["dsh-score"]: { name: "评分", desc: "插件质量评分：按检查项评估插件并产出证据化合规报告。", nameEn: "Score", descEn: "Plugin quality scoring: evaluates plugins per checklist item and produces evidence-backed compliance reports.", category: "tool" as PluginCategory },
  ["dsh-test-drive"]: { name: "试驾", desc: "在一次性沙箱环境（临时 DSH_HOME）试跑插件并输出 JSON/Markdown 评分。", nameEn: "Test drive", descEn: "Trials plugins in a disposable sandbox (temporary DSH_HOME) and emits JSON/Markdown score reports.", category: "tool" as PluginCategory },
  ["dsh-defend"]: { name: "防御", desc: "提示注入、越狱与密钥泄露防御：Aho-Corasick 检测 + allow/ask/block 拦截 + 递归删除执行前门。", nameEn: "Defend", descEn: "Defense against prompt injection, jailbreaks and secret leakage: Aho-Corasick detection + allow/ask/block interception + a pre-execution gate for recursive deletes.", category: "sandbox" as PluginCategory },
  ["dsh-budget"]: { name: "预算", desc: "成本治理：按模型/会话/天聚合 token 与费用、预算上限与阈值告警、碳足迹估算、/budget 命令。", nameEn: "Budget", descEn: "Cost governance: token and cost aggregation per model/session/day, budget caps and threshold alerts, carbon footprint estimates and the /budget command.", category: "tool" as PluginCategory },
  ["dsh-fast"]: { name: "快检", desc: "只读性能诊断：会话加载/恢复耗时、溢写命中、压缩次数、上下文注入量、LLM 缓存命中率（/fast）。", nameEn: "Fast check", descEn: "Read-only performance diagnostics: session load/restore times, spill hits, compaction counts, context injection volume and LLM cache hit rate (/fast).", category: "tool" as PluginCategory },
  ["dsh-observe"]: { name: "可观测", desc: "可观测性：请求追踪、遥测、日志缓冲与重试可见性。", nameEn: "Observe", descEn: "Observability: request tracing, telemetry, log buffering and retry visibility.", category: "tool" as PluginCategory },
  ["dsh-click"]: { name: "桌面控制", desc: "跨平台原生桌面控制（Windows 优先）：截图、读屏、点击/键入/滚动/按键、应用列表与启动——审批门 + 不抢焦点。", nameEn: "Desktop control", descEn: "Cross-platform native desktop control (Windows first): screenshots, screen reading, click/type/scroll/keys, app listing and launching — approval-gated and never steals focus.", category: "tool" as PluginCategory },
  ["dsh-talk"]: { name: "语音", desc: "语音能力：文本转语音与语音转文本，带静音与说即聊控制。", nameEn: "Voice", descEn: "Voice capabilities: text-to-speech and speech-to-text with mute and push-to-talk controls.", category: "tool" as PluginCategory },
  ["dsh-draw"]: { name: "绘图", desc: "统一 image_generate 工具：OpenAI Images / Zhipu CogView 路由、健康感知回退、会话配额记账。", nameEn: "Draw", descEn: "Unified image_generate tool: OpenAI Images / Zhipu CogView routing, health-aware fallback and per-session quota accounting.", category: "tool" as PluginCategory },
  ["dsh-industry-research"]: { name: "行业研究", desc: "结构化公司/行业深研：来源捕获 + 可审计研究轨迹。", nameEn: "Industry research", descEn: "Structured company/industry deep research: source capture + an auditable research trail.", category: "tool" as PluginCategory },
  ["dsh-research-report"]: { name: "研究报告", desc: "证据链研究报告：内容哈希封印来源目录，报告与来源不可分。", nameEn: "Research report", descEn: "Evidence-chain research reports: the source catalog is sealed by content hashes and cannot be separated from the report.", category: "tool" as PluginCategory },
  ["dsh-fund-research"]: { name: "基金研究", desc: "基金分析：收益、持仓与绩效归因。", nameEn: "Fund research", descEn: "Fund analysis: returns, holdings and performance attribution.", category: "tool" as PluginCategory },
  ["dsh-library"]: { name: "知识库", desc: "本地文档知识库：语义+关键词混合检索、引用感知注入、SQLite 索引、本地嵌入零模型下载。", nameEn: "Library", descEn: "Local document knowledge base: hybrid semantic+keyword retrieval, citation-aware injection, SQLite indexing and local embeddings with zero model downloads.", category: "tool" as PluginCategory },
  ["dsh-plugin-guide"]: { name: "插件指南", desc: "可安装的 DSH 插件开发指南技能：打包、契约、检查与构建校验器。", nameEn: "Plugin guide", descEn: "Installable DSH plugin development guide skill: packaging, contracts, checks and build validators.", category: "skill" as PluginCategory },
  ["@perrylink/dsh-github"]: { name: "GitHub", desc: "GitHub 集成：PR/issue/仓库/文件工具、评审与 CI 检查——写操作全审批门、token 不落日志。", nameEn: "GitHub", descEn: "GitHub integration: PR/issue/repo/file tools, reviews and CI checks — all writes approval-gated, tokens never logged.", category: "tool" as PluginCategory },
  ["@perrylink/dsh-skill-pack-security-provider"]: { name: "安全技能包", desc: "预打包安全评审技能 + 风险卡：host 与 client 双端交付。", nameEn: "Security skill pack", descEn: "Pre-packaged security review skills + risk cards: delivered to both host and client.", category: "skill" as PluginCategory },
  ["dsh-personal-directive"]: { name: "个人指令", desc: "顶部栏一键开关的个人指令插件（框架版：中性占位指令，可替换为自己的内容）。", nameEn: "Personal directive", descEn: "One-click personal-directive plugin in the top bar (framework edition: neutral placeholder directive, replace it with your own).", category: "agent" as PluginCategory },
  ["@perrylink/dsh-ticktick"]: { name: "TickTick 任务桥", desc: "TickTick（滴答清单）任务桥：会话头任务面板 + 11 个精选 ticktick_* 工具 + 官方 MCP 端点上的设置卡片。", nameEn: "TickTick bridge", descEn: "TickTick task bridge: a session-header task panel + 11 curated ticktick_* tools + a settings card on the official MCP endpoint.", category: "tool" as PluginCategory },
  ["@perrylink/dsh-cert-mcp"]: { name: "认证 MCP", desc: "只读 MCP 服务器：暴露插件认证等级、快照与五维证据。", nameEn: "Certification MCP", descEn: "Read-only MCP server exposing plugin certification levels, snapshots and five-dimension evidence.", category: "tool" as PluginCategory },
  ["dsh-reach"]: { name: "触达", desc: "多通道决策与遥控桥：审批/提问卡片镜像到 IM（微信 iLink、Telegram、飞书），#token 稳定 id，聊天内直接应答。", nameEn: "Reach", descEn: "Multi-channel decision and remote-control bridge: mirrors approval/question cards to IM (WeChat iLink, Telegram, Feishu), stable #token ids, replies directly from chat.", category: "tool" as PluginCategory },
  ["dsh-autotier"]: { name: "自动分档", desc: "强/便宜模型分档路由：意图门控落档、计划模式交接（强档规划便宜档执行）、工具/执行前高危守卫、TTL 回退。", nameEn: "Auto tiering", descEn: "Strong/cheap model tier routing: intent-gated tier assignment, plan-mode handoff (strong tier plans, cheap tier executes), pre-tool/pre-execution danger guards and TTL fallback.", category: "llm" as PluginCategory },
  // dsh-plugin-upgrade: skip (not in master table)；dsh-plugin-upgrade-rc1 为一次性历史迁移包，不入目录
  ["@dsh-external/dsh-navbar"]: { name: "对话导航条", desc: "对话区右缘的消息节点导航（第三方插件）", nameEn: "Conversation scrollbar", descEn: "Message-node navigation on the right edge of the conversation area (third-party plugin)", category: "ui" as PluginCategory },
  // ===== DSH 0.2.0 新增/拆分的内置行（数据源：0.2.0-rc.2 dsh-base / dsh-web-app 捆绑补丁 + 各包 package.json description）=====
  ["@deepseek-ai/dsh-hmr"]: { name: "热加载驱动（0.2.0+）", desc: "协调模块与 profile 配置的热重载（0.2.0 起替代 cordis-plugin-hmr，监听全局与 profile 补丁文件）", nameEn: "Hot reload driver (0.2.0+)", descEn: "Coordinates hot reload for modules and profile config (replaces cordis-plugin-hmr in 0.2.0; watches global and profile patch files)", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-settings"]: { name: "设置服务", desc: "用户设置缝（ctx.settings）：设置文档读取与命名空间作用域", nameEn: "Settings service", descEn: "User settings seam (ctx.settings): settings document reads and namespace scoping", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-config-editor"]: { name: "配置编辑器", desc: "把插件配置持久化进 profile 补丁并经加载器对账热生效", nameEn: "Config editor", descEn: "Persists plugin config into profile patches and reconciles it hot through the loader", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-authorization"]: { name: "授权缝", desc: "插件自有凭据获取流程（ctx.authorization）：与用户对话取得凭据", nameEn: "Authorization seam", descEn: "Plugin-owned credential flows (ctx.authorization): obtains credentials by talking to the user", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-otel"]: { name: "OTLP 遥测通道", desc: "普通事件与会话日志的 OTLP 上报（可关闭）", nameEn: "OTLP telemetry", descEn: "OTLP reporting for ordinary events and session logs (opt-out)", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-plugin-package-inventory-deepseek"]: { name: "插件清单投影", desc: "把加载器中的插件包清单投喂给官方 DeepSeek 模型请求", nameEn: "Plugin package inventory", descEn: "Feeds the loader's plugin package inventory into official DeepSeek model requests", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-plugin-manager"]: { name: "官方插件管理服务", desc: "dsh CLI/Web/agent 工具共享的 profile 插件与捆绑管理（0.2.0+）；与本插件的行同 id 时由本插件替换", nameEn: "Official plugin management", descEn: "Profile plugin and bundle management shared by dsh CLI/Web/agent tooling (0.2.0+); replaced by this plugin when row ids collide", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-deepseek-account-platform"]: { name: "DeepSeek 账号授权", desc: "通过浏览器 PKCE 流程授权 DeepSeek 账号", nameEn: "DeepSeek account auth", descEn: "Authorizes DeepSeek accounts via the browser PKCE flow", category: "llm" as PluginCategory },
  ["@deepseek-ai/dsh-deepseek-llm-api-extensions"]: { name: "DeepSeek 请求扩展注册", desc: "官方 DeepSeek 模型适配的增量请求字段注册表", nameEn: "DeepSeek request extensions", descEn: "Registry of incremental request fields for the official DeepSeek model adapter", category: "llm" as PluginCategory },
  ["@deepseek-ai/dsh-llm-deepseek-api-key"]: { name: "DeepSeek API Key 适配", desc: "DeepSeek api-key 提供者的认证与模型发现", nameEn: "DeepSeek API key adapter", descEn: "Auth and model discovery for the DeepSeek api-key provider", category: "llm" as PluginCategory },
  ["@deepseek-ai/dsh-llm-deepseek-account"]: { name: "DeepSeek 账号适配", desc: "DeepSeek 账号提供者的认证与模型发现", nameEn: "DeepSeek account adapter", descEn: "Auth and model discovery for the DeepSeek account provider", category: "llm" as PluginCategory },
  ["@deepseek-ai/dsh-session-log-deepseek"]: { name: "会话日志请求扩展", desc: "官方 DeepSeek 适配的会话日志增量无损请求扩展", nameEn: "Session log request extensions", descEn: "Lossless incremental session-log request extensions for the official DeepSeek adapter", category: "session" as PluginCategory },
  ["@deepseek-ai/dsh-compaction-image-offload"]: { name: "图片溢写压缩", desc: "图片预算超限时把最旧图片替换为占位符并重试", nameEn: "Image offload compaction", descEn: "Replaces the oldest images with placeholders when the image budget is exceeded and retries", category: "session" as PluginCategory },
  ["@deepseek-ai/dsh-ptc-runtime-node"]: { name: "PTC 执行运行时", desc: "沙箱化 Node 进程实现的 PTC 执行能力", nameEn: "PTC execution runtime", descEn: "PTC execution capability backed by sandboxed Node processes", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-workflow-ptc"]: { name: "PTC 工作流", desc: "在共享 PTC 沙箱运行时中编排工作流脚本", nameEn: "PTC workflow", descEn: "Orchestrates workflow scripts in the shared PTC sandbox runtime", category: "agent" as PluginCategory },
  ["@deepseek-ai/dsh-web-fetch-http"]: { name: "HTTP 抓取提供者", desc: "ctx.web 的匿名公网 HTTP(S) 抓取提供者", nameEn: "HTTP fetch provider", descEn: "Anonymous public HTTP(S) fetch provider for ctx.web", category: "web" as PluginCategory },
  ["@deepseek-ai/dsh-mcp-resources"]: { name: "MCP 资源", desc: "经共享模型工具做作用域内的 MCP 资源发现与读取", nameEn: "MCP resources", descEn: "Scoped MCP resource discovery and reads through shared model tools", category: "tool" as PluginCategory },
  ["@deepseek-ai/dsh-client-resources"]: { name: "客户端资源模型", desc: "URL 地址经协议注册的提供者变为可用值（useResource 钩子）", nameEn: "Client resources", descEn: "URLs become usable values through protocol-registered providers (useResource hook)", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-client-shortcuts"]: { name: "快捷键注册", desc: "应用键盘命令注册与物理键路由", nameEn: "Shortcut registration", descEn: "App keyboard command registration and physical key routing", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-file-upload"]: { name: "文件上传", desc: "Agent 作用域的浏览器文件上传、流入与暂存服务", nameEn: "File upload", descEn: "Agent-scoped browser file upload, inflow and staging service", category: "core" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-renderer"]: { name: "界面渲染器", desc: "React 槽位绑定、ctx.uiRenderer 与组装后的应用根（0.2.0 起接管客户端运行时职责）", nameEn: "UI renderer", descEn: "React slot binding, ctx.uiRenderer and the assembled app root (takes over client-runtime duties from 0.2.0)", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-session"]: { name: "会话控制器适配", desc: "会话控制器的 React 适配与会话作用域槽位", nameEn: "Session controller adapter", descEn: "React adapter for the session controller and session-scoped slots", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-chat"]: { name: "会话目标界面", desc: "Chat Conversation 目标、节点定义、渲染器与详情面板", nameEn: "Chat conversation UI", descEn: "Chat Conversation target, node definitions, renderers and detail panels", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-approval"]: { name: "审批卡片", desc: "经作用域远程事件接管审批编排的对话卡片", nameEn: "Approval cards", descEn: "Conversation cards taking over approval orchestration via scoped remote events", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-shortcuts"]: { name: "快捷键面板", desc: "快捷键参考、录制与本地偏好编辑", nameEn: "Shortcuts panel", descEn: "Shortcut reference, recording and local preference editing", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-settings-account"]: { name: "账号设置", desc: "管理 DeepSeek 登录与开放平台账单页入口", nameEn: "Account settings", descEn: "Manages DeepSeek sign-in and the open-platform billing page entry", category: "ui" as PluginCategory },
  ["@deepseek-ai/dsh-client-ui-plugin-manager"]: { name: "官方插件面板", desc: "官方侧边栏插件面板：安装/启停/重试/组合插件包（0.2.0+，与本插件的设置页标签互不冲突）", nameEn: "Official plugin panel", descEn: "Official sidebar plugin panel: install/enable/retry/bundle plugins (0.2.0+; does not conflict with this plugin's settings tab)", category: "ui" as PluginCategory },
}

/** 系统保护模块：缺失会导致应用/传输层/插件管家自身失效，界面不允许停用。 */
export const SYSTEM_MODULES: ReadonlySet<string> = new Set([
  // 基础运行时与热加载
  '@deepseek-ai/cordis-plugin-timer',
  '@deepseek-ai/cordis-plugin-hmr',
  '@deepseek-ai/dsh-hmr',
  // 类型反射与 RPC
  '@deepseek-ai/dsh-typert-registry',
  '@deepseek-ai/dsh-typert-loader',
  '@deepseek-ai/dsh-api-gateway',
  '@deepseek-ai/dsh-host-apiproxy',
  // 大模型与工具管线（停用后 Agent 无法工作）
  '@deepseek-ai/dsh-llm',
  '@deepseek-ai/dsh-tools',
  '@deepseek-ai/dsh-system-prompt',
  '@deepseek-ai/dsh-agent',
  '@deepseek-ai/dsh-agent-loop',
  '@deepseek-ai/dsh-session',
  '@deepseek-ai/dsh-session-persistence-jsonl',
  // 设置与凭据存储
  '@deepseek-ai/dsh-settings',
  '@deepseek-ai/dsh-settings-file',
  '@deepseek-ai/dsh-storage',
  '@deepseek-ai/dsh-storage-json',
  '@deepseek-ai/dsh-storage-domain',
  // 沙箱基础
  '@deepseek-ai/dsh-sandbox-local',
  '@deepseek-ai/dsh-sandbox-policy',
  '@deepseek-ai/dsh-fs-sandbox',
  // Web 宿主与传输
  '@deepseek-ai/dsh-host-webserver',
  '@deepseek-ai/dsh-web-app',
  '@deepseek-ai/dsh-web-app/startup',
  '@deepseek-ai/dsh-client-modules',
  '@deepseek-ai/dsh-client-connection',
  '@deepseek-ai/dsh-api-remotes',
  '@deepseek-ai/dsh-client-runtime',
  // 设置页外壳（插件管家标签页的宿主）
  '@deepseek-ai/dsh-client-ui-settings',
  '@deepseek-ai/dsh-client-ui-settings-plugins',
  '@deepseek-ai/dsh-client-locale',
  '@deepseek-ai/dsh-client-ui-layout',
  // 插件管家自身
  '@txc2768651338/dsh-plugin-manager',
])

/** 按行 id 保护（与模块名无关的引导行，如 include 根）。 */
export const SYSTEM_ROW_IDS: ReadonlySet<string> = new Set([
  'include',
  'loader',
  'plugin-manager',
])

/** 目录里未收录时的默认说明。 */
export const FALLBACK_DESC = '该插件暂无内置说明，可在覆盖文件中补充自定义说明。'

/** 英文界面下未收录/无英文说明时的默认说明（评估 P2-9，与 FALLBACK_DESC 对应）。 */
export const FALLBACK_DESC_EN = 'No built-in description yet. Add a custom note in the override file.'
